name: CI & Deploy → GoDaddy Shared (Optimized FTP)

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: massage_course

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install & build React
        working-directory: ./massage-course-platform
        run: |
          npm ci
          npm run build

      - name: Copy React build → Laravel public
        run: |
          rm -rf massage-course-backend/public/*
          cp -R massage-course-platform/dist/* massage-course-backend/public/

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, tokenizer, xml, json, openssl, fileinfo
      - name: Install & optimize Laravel
        working-directory: ./massage-course-backend
        run: |
          composer install --no-dev --optimize-autoloader
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Deploy with optimized settings
      - name: Deploy backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: massage-course-backend/
          server-dir: /home/${{ secrets.FTP_USERNAME }}/massage-course-backend/
          # Optimization settings
          exclude: |
            **/public/**
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
          # Only upload changed files
          state-name: .ftp-deploy-sync-backend-state.json
          dry-run: false
          log-level: minimal

      - name: Deploy frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: massage-course-backend/public/
          server-dir: /home/${{ secrets.FTP_USERNAME }}/public_html/
          # Only upload changed files
          state-name: .ftp-deploy-sync-frontend-state.json
          dry-run: false
          log-level: minimal